### ISSUE TITLE
Mutating the Prototype of an object cause your code to run very slowly lai_collection-extensions.js:97:5

### ISSUE THREAD

**Issue by tizol** [rclai/meteor-collection-extensions#13] opened 2016-01-20 06:17 UTC
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create lai_collection-extensions.js:97:5

I got this error while running a meteor app with this package.

**Comment by rclai** [comment] 2016-01-27 16:16
Duplicate of #10.

**Closed by rclai** 2016-01-27 16:16 UTC
